name:                tests-haskell
version:             0.1.0.0
github:              "kajigor/tests-haskell"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/tests-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  tests-haskell-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tests-haskell
    - tasty
    - tasty-hunit
    - tasty-discover

